// Generates dist/tokens.css: semantic roles as RGB-channel custom properties.
// Dark is the default; [data-theme="light"] switches to the light set.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dark, light, colorRoles, type ColorRole } from '../src/semantic';
import { cssVar, hexToChannels } from '../src/color';
import { fonts } from '../src/scale';

const block = (set: Record<ColorRole, string>) =>
  colorRoles.map((role) => `  ${cssVar(role)}: ${hexToChannels(set[role])}; /* ${set[role]} */`).join('\n');

const css = `/* Generated by @ost/tokens — do not edit. Source: src/semantic.ts */
:root {
  color-scheme: dark;
  --ost-font-sans: ${fonts.sans.map((f) => (f.includes(' ') ? `'${f}'` : f)).join(', ')};
${block(dark)}
}

[data-theme='light'] {
  color-scheme: light;
${block(light)}
}
`;

mkdirSync('dist', { recursive: true });
writeFileSync('dist/tokens.css', css);
console.log('wrote dist/tokens.css');
